"""api migration

Revision ID: c63e76ad7dfc
Revises: 67bf54dbf4ad
Create Date: 2025-06-25 18:34:58.480767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c63e76ad7dfc'
down_revision: Union[str, None] = '67bf54dbf4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allergy')
    op.drop_table('food_suggestion')
    op.drop_table('drink')
    op.drop_table('health')
    op.drop_index(op.f('ix_drink_suggestion_suggestion_id'), table_name='drink_suggestion')
    op.drop_table('drink_suggestion')
    op.drop_index(op.f('ix_user_preference_preference_id'), table_name='user_preference')
    op.drop_table('user_preference')
    op.drop_table('food')
    op.drop_table('student')
    op.drop_table('device')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['Student'::character varying, 'Admin'::character varying, 'Teacher'::character varying]::text[])", name='student_role_check'),
    sa.CheckConstraint('date_of_birth < CURRENT_DATE', name='student_date_of_birth_check'),
    sa.PrimaryKeyConstraint('user_id', name='student_pkey'),
    sa.UniqueConstraint('email', name='student_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('food',
    sa.Column('food_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('food_items', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('intake_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('calories_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbohydrates_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cholesterol_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.CheckConstraint('calories_estimate IS NULL OR calories_estimate >= 0::double precision', name=op.f('food_calories_estimate_check')),
    sa.CheckConstraint('intake_time <= CURRENT_TIMESTAMP', name=op.f('food_intake_time_check')),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('food_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('food_id', name=op.f('food_pkey'))
    )
    op.create_table('user_preference',
    sa.Column('preference_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('preferred_meal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_drink_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dietary_restrictions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('preffered_allergy', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('preferred_meal_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('meals_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disease', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('user_preference_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preference_id', name=op.f('user_preference_pkey'))
    )
    op.create_index(op.f('ix_user_preference_preference_id'), 'user_preference', ['preference_id'], unique=False)
    op.create_table('drink_suggestion',
    sa.Column('suggestion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('drink_sg', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.Column('generated_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('suggestion_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('drink_suggestion_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('suggestion_id', name=op.f('drink_suggestion_pkey'))
    )
    op.create_index(op.f('ix_drink_suggestion_suggestion_id'), 'drink_suggestion', ['suggestion_id'], unique=False)
    op.create_table('health',
    sa.Column('health_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('heart_rate_bpm', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('systolic_bp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diastolic_bp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('measurement_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('diastolic_bp > 0', name=op.f('health_diastolic_bp_check')),
    sa.CheckConstraint('heart_rate_bpm > 0', name=op.f('health_heart_rate_bpm_check')),
    sa.CheckConstraint('height_m IS NULL OR height_m > 0::double precision', name=op.f('health_height_m_check')),
    sa.CheckConstraint('measurement_time <= CURRENT_TIMESTAMP', name=op.f('health_measurement_time_check')),
    sa.CheckConstraint('systolic_bp > 0', name=op.f('health_systolic_bp_check')),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0::double precision', name=op.f('health_weight_kg_check')),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], name=op.f('health_device_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('health_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('health_id', name=op.f('health_pkey'))
    )
    op.create_table('drink',
    sa.Column('drink_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('drink_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sugar_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drink_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('caffeine_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('potassium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.CheckConstraint('sugar_g IS NULL OR sugar_g >= 0::double precision', name=op.f('drink_sugar_g_check')),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('drink_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drink_id', name=op.f('drink_pkey'))
    )
    op.create_table('device',
    sa.Column('device_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.CheckConstraint("device_type::text = 'Wearable'::text", name=op.f('device_device_type_check')),
    sa.CheckConstraint('registration_date <= CURRENT_DATE', name=op.f('device_registration_date_check')),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('device_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', name=op.f('device_pkey'))
    )
    op.create_table('food_suggestion',
    sa.Column('suggestion_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('based_on_bp', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('food_sg', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('drink_sg', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('generated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("based_on_bp::text = ANY (ARRAY['High BP'::character varying, 'Low BP'::character varying, 'Normal'::character varying]::text[])", name=op.f('food_suggestion_based_on_bp_check')),
    sa.CheckConstraint("drink_sg::text = 'reduce the Consumption of Sugar and Alcohol'::text", name=op.f('food_suggestion_drink_sg_check')),
    sa.CheckConstraint("food_sg::text = 'Reduce consumption of Fast Food'::text", name=op.f('food_suggestion_food_sg_check')),
    sa.CheckConstraint('generated_on <= CURRENT_TIMESTAMP', name=op.f('food_suggestion_generated_on_check')),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('food_suggestion_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('suggestion_id', name=op.f('food_suggestion_pkey'))
    )
    op.create_table('allergy',
    sa.Column('allergy_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allergy_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("allergy_type::text = ANY (ARRAY['Hypertension'::character varying, 'Diabetes'::character varying, 'Asthma'::character varying, 'Peanut Allergy'::character varying, 'Lactose Intolerance'::character varying]::text[])", name=op.f('allergy_allergy_type_check')),
    sa.ForeignKeyConstraint(['user_id'], ['student.user_id'], name=op.f('allergy_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allergy_id', name=op.f('allergy_pkey'))
    )
    # ### end Alembic commands ###
